(defun my-set-left (n)
  (interactive "nSet left margin:")
  (back-to-indentation)
  (delete-horizontal-space) 
  (dotimes (i n)
    (insert " "))
)
(global-set-key (kbd "M-g M-d") 'my-set-left)

(defun my-dedent-left (n)
  (interactive "nDecrease left margin:")
  (back-to-indentation)
  (backward-delete-char n)
)
(global-set-key (kbd "M-g M-f") 'my-dedent-left)

(defun my-indent-left (n) 
  (interactive "nIncrease left margin:")
  (back-to-indentation)
  (dotimes (i n)
    (insert " "))
)
(global-set-key (kbd "M-g M-h") 'my-indent-left)
